org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.enableAapt2FromMaven=true
android.aapt2Version=8.6.1-11315950
# exact match for AGP 8.6.1
#org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-11.0.24.8-hotspot